// src/pages/MonumentDetails.js
import React, { } from 'react';
import { useParams } from 'react-router-dom';
import './MonumentDetails.css';

const monumentsData = [
  { id: 1, name: 'Taj Mahal', description: 'The Taj Mahal, located on the banks of the Yamuna River in Agra, Uttar Pradesh, India, stands as one of the greatest architectural achievements of the Mughal Empire and a symbol of eternal love. Commissioned in 1632 by Emperor Shah Jahan in memory of his beloved wife, Mumtaz Mahal, the mausoleum complex took over 20 years to complete, with thousands of artisans and craftsmen contributing to its creation.\n\nThe mausoleum is constructed entirely of white marble, which appears to change color depending on the time of day, from pinkish hues at sunrise to sparkling white at noon and golden tones at sunset. The main structure sits on a square plinth, topped with a large, central dome and surrounded by four minarets. The dome, an architectural marvel in itself, rises to a height of 73 meters (240 feet), and its perfect symmetry exemplifies Mughal architecture.\n\nThe Taj Mahal is adorned with intricate carvings, calligraphy of verses from the Quran, and inlaid precious and semi-precious stones, including jasper and jade, that form delicate floral patterns in a technique called pietra dura. The interiors feature a central chamber with the cenotaphs of Mumtaz Mahal and Shah Jahan (the actual tombs are below, in a lower chamber), as well as decorative lattice screens made of marble.\n\nSurrounding the main mausoleum are extensive gardens laid out in the Charbagh (four-part garden) style, symbolizing paradise in Islamic tradition. The garden is divided by pathways and water channels that reflect the monument, enhancing its ethereal beauty.'},
  { id: 2, name: 'Red Fort', description: 'The Red Fort, or Lal Qila, is a historic fortress in Delhi, India, built in 1648 by Mughal Emperor Shah Jahan. Known for its towering red sandstone walls that stretch over 2 kilometers, the fort is an architectural marvel blending Persian, Timurid, and Indian styles. It served as the Mughal emperors main residence for nearly 200 years and is a testament to the grandeur of the Mughal era.\n\nInside, the Red Fort houses various stunning structures. The Diwan-i-Aam (Hall of Public Audience) and Diwan-i-Khas (Hall of Private Audience) are notable halls where the emperor addressed subjects and dignitaries. The Rang Mahal (Palace of Colors) and Mumtaz Mahal are adorned with beautiful floral designs, and the Moti Masjid (Pearl Mosque), built by Aurangzeb, stands out with its serene white marble.\n\nEvery year on India\'s Independence Day, the Prime Minister hoists the national flag at the fort, a tradition symbolizing its importance in India’s history. As a UNESCO World Heritage Site, the Red Fort attracts millions of visitors, offering them a glimpse into the legacy and cultural richness of India’s past.'},
  { id: 3, name: 'Qutub Minar', description: `Qutub Minar is a towering minaret in Delhi, India, and one of the most famous landmarks of Indo-Islamic architecture. Constructed in 1193 by Qutb-ud-din Aibak, the first ruler of the Delhi Sultanate, this remarkable structure stands at 73 meters (240 feet), making it the tallest brick minaret in the world. Built primarily as a victory tower to signify Muslim dominance in Delhi after the defeat of the last Hindu kingdom, Qutub Minar has intricate carvings and verses from the Quran inscribed on its red sandstone and marble surface. The structure consists of five distinct stories, each marked by a balcony, and tapers as it rises from a 14.3-meter base to a 2.7-meter summit. Although Aibak initiated its construction, it was completed by his successor, Iltutmish, who added three more stories. Firoz Shah Tughlaq later renovated and added the fifth story after an earthquake damaged the minar.
    Qutub Minar is surrounded by the Qutub Complex, which includes historical structures like the Quwwat-ul-Islam Mosque, the oldest mosque in India, and the Iron Pillar, a 4th-century marvel known for its rust-resistant iron composition. As a UNESCO World Heritage Site, Qutub Minar attracts millions, showcasing the rich historical legacy of medieval India.`},
  { id: 4, name: 'Gateway of India', description: `The Gateway of India is an iconic arch monument located in Mumbai, India, overlooking the Arabian Sea. Built in 1911 to commemorate the visit of King George V and Queen Mary, it serves as a symbol of India's colonial history. The gateway stands 26 meters tall and features a stunning Indo-Saracenic architectural style, combining elements of Hindu and Muslim design. The monument is constructed from yellow basalt stone, with intricate latticework and beautiful carvings that showcase the craftsmanship of the era.
  Surrounded by vibrant promenades and bustling activity, the Gateway of India is often the starting point for ferry rides to Elephanta Island, famous for its ancient rock-cut temples. The area is also adorned with the majestic Taj Mahal Palace Hotel, making it a popular destination for tourists and locals alike.
  The Gateway has witnessed significant historical events, including the departure of the last British troops from India in 1948, marking the end of British rule. Today, it stands as a symbol of national pride and resilience, attracting millions of visitors each year who come to appreciate its historical significance and enjoy the lively atmosphere around this remarkable structure.`},
  { id: 5, name: 'Charminar', description: `The Charminar is a historic monument located in the heart of Hyderabad, India, and is an iconic symbol of the city. Built in 1591 by Muhammad Quli Qutb Shah, the Charminar was erected to commemorate the end of a devastating plague and serves as a grand gateway to the old city. The monument is characterized by its four majestic arches that face each cardinal direction, each arch measuring 11 meters wide and 20 meters high, creating a stunning entrance to the bustling market area. 
  Standing at 56 meters tall, the Charminar features minarets that rise to a height of 48.7 meters and are adorned with intricate stucco decorations. The structure is built from a combination of granite and limestone, showcasing a beautiful blend of Islamic architecture with elements of Persian design. The monument is surrounded by vibrant bazaars, where visitors can shop for traditional textiles, jewelry, and street food.
  The Charminar is not only a symbol of Hyderabad's rich heritage but also an important cultural hub, attracting tourists and locals alike. As a UNESCO World Heritage Site, it stands as a testament to the city's historical significance and architectural brilliance, embodying the spirit of Hyderabad.`},
  { id: 6, name: 'Mysore Palace', description: `The Mysore Palace, located in the city of Mysore, India, is a stunning example of Indo-Saracenic architecture and one of the most visited tourist attractions in the country. Originally built in the 14th century, the palace was reconstructed in the early 20th century after a fire destroyed much of the original structure. The current design, completed in 1912, features a blend of architectural styles, including Gothic, Rajput, and Islamic influences.
  The palace is known for its grandiose structure, with its five-story façade adorned with intricate carvings, domes, and towers. The main entrance, called the Amba Vilas, is particularly striking, flanked by ornate arches and embellished with beautiful stained glass. Inside, the palace boasts opulent interiors with elaborately decorated halls, including the Durbar Hall, where royal ceremonies were held.
  During the Dussehra festival, the palace is illuminated with thousands of lights, creating a mesmerizing spectacle. As a UNESCO World Heritage Site, the Mysore Palace reflects the rich history of the Wodeyar dynasty and stands as a testament to the architectural brilliance and cultural heritage of Karnataka, captivating visitors with its beauty and grandeur.`},
  { id: 7, name: 'Sun Temple, Konark', description:  `The Sun Temple, located in Konark, Odisha, is a UNESCO World Heritage Site and a remarkable example of ancient Indian architecture dedicated to the Sun God, Surya. Built in the 13th century during the reign of King Narasimhadeva I of the Eastern Ganga Dynasty, the temple is designed in the shape of a gigantic chariot, drawn by seven horses on twelve pairs of intricately carved wheels.
    Constructed from Khondalite stone, the temple showcases exquisite craftsmanship with intricate carvings depicting various deities, celestial beings, and scenes from everyday life in ancient India. The main sanctum once housed a colossal idol of the Sun God, though it was destroyed over time.
    The temple's architectural brilliance is not only in its structure but also in its alignment with the sun. The rays of the sun illuminate the main entrance at dawn, creating a breathtaking view.
    The Sun Temple is surrounded by a beautiful garden, enhancing its aesthetic appeal. As a significant cultural and religious landmark, the Konark Sun Temple attracts pilgrims and tourists alike, symbolizing the grandeur of ancient Indian architecture and its enduring spiritual significance.` },
  { id: 8, name: 'Golconda Fort', description: `Golconda Fort, located near Hyderabad, India, is a historic fortress renowned for its architectural brilliance and rich history. Originally built in the 12th century by the Kakatiya dynasty, it was later expanded by the Qutb Shahi dynasty, transforming it into a formidable stronghold. The fort is strategically perched on a hill, offering stunning views of the surrounding landscape.
  The fort's design includes massive granite walls, towering gates, and an intricate system of acoustics that allowed guards to communicate across vast distances. The Balahisar Gate is particularly famous for its impressive architecture. Within the fort complex, visitors can explore numerous palaces, temples, and mosques, showcasing the splendor of the bygone era.
  Golconda Fort is also known for its association with the diamond trade, as it was the original mine site of some of the world’s most famous diamonds, including the Koh-i-Noor.
  The fort’s historical significance, combined with its stunning architecture, makes it a popular tourist destination. Each evening, a sound and light show narrates the fort’s history, adding to the charm of this magnificent monument, which stands as a testament to the grandeur of the Deccan Sultanate.`},
  { id: 9, name: 'Victoria Memorial', description: `The Victoria Memorial is an exquisite monument located in Kolkata, India, dedicated to Queen Victoria of the United Kingdom. Built between 1906 and 1921, it was commissioned by the British Raj to honor her memory following her death in 1901. Designed by the British architect William Emerson, the memorial showcases a blend of European and Mughal architectural styles, primarily using white Makrana marble, which lends it an ethereal quality.
  The monument is surrounded by lush gardens spanning over 64 acres, featuring beautifully landscaped lawns, fountains, and statues. At the center stands the magnificent dome, rising to a height of 56 meters, adorned with allegorical sculptures representing Art, Commerce, and Science. Inside, the memorial houses a museum displaying a rich collection of paintings, artifacts, and memorabilia related to the British colonial era.
  The Victoria Memorial serves not only as a tribute to Queen Victoria but also as a symbol of Kolkata's cultural heritage. It attracts millions of visitors each year, offering a serene retreat amidst the hustle and bustle of the city. As a significant landmark, it stands as a testament to the historical and architectural legacy of British India.`},
];

const MonumentDetails = () => {
  const { id } = useParams();
  const monument = monumentsData.find((m) => m.id === parseInt(id));

  if (!monument) {
    return <div>Monument not found.</div>;
  }

  return (
    <div
      style={{
        padding: '20px',
        textAlign: 'center',
        backgroundImage: 'url(/images/Monuments.png)', // Path should be relative to public/
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        color: 'white',
      }}
    >
      <h2>{monument.name}</h2>
      <p>{monument.description}</p>
    </div>
  );
};

export default MonumentDetails;